;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "lein-deps-tree-skill")
(def path ".")
(def version "0.1.1")
(def tag "0.1.1")
(def generated-at "2020-06-15T18:46:50Z")
