FROM clojure:lein-2.8.1

LABEL maintainer="Jim Clark <jim@atomist.com>"

RUN apt-get update && apt-get install -y \
        curl \
        gnupg \
        build-essential \
        dumb-init

RUN curl -sL https://deb.nodesource.com/setup_12.x  | bash - \
    && apt-get -y install nodejs

RUN curl -O https://download.clojure.org/install/linux-install-1.10.1.462.sh \
    && chmod +x linux-install-1.10.1.462.sh \
    && ./linux-install-1.10.1.462.sh

